using System;
using System.Collections.Generic;
using System.Numerics;
using System.Text.Json.Nodes;

namespace SharpGLTF.Schema2.Tiles3D
{
    // Public API of the extensions defined in the glTF 2.1 3D Tiles vendor extensions (3d-tiles-2.0 branch).
    // The serialization code is generated by SharpGLTF.CodeGen.Extensions.Cesium, see Schema2/Generated.

    #region EXT_georeference and EXT_geospatial_crs

    /// <summary>
    /// EXT_georeference extension, attached to a <see cref="Node"/>.
    /// </summary>
    partial class ExtGeoreferenceNode
    {
        /// <summary>Longitude in degrees, in the range [-180, 180].</summary>
        public double Longitude
        {
            get => _longitude;
            set { Guard.MustBeBetweenOrEqualTo(value, _longitudeMinimum, _longitudeMaximum, nameof(value)); _longitude = value; }
        }

        /// <summary>Latitude in degrees, in the range [-90, 90].</summary>
        public double Latitude
        {
            get => _latitude;
            set { Guard.MustBeBetweenOrEqualTo(value, _latitudeMinimum, _latitudeMaximum, nameof(value)); _latitude = value; }
        }

        /// <summary>Height above (or below) the ellipsoid in meters.</summary>
        public double? Height { get => _height; set => _height = value; }
    }

    /// <summary>
    /// EXT_geospatial_crs extension, attached to a <see cref="ModelRoot"/>.
    /// The CRS definition is provided by a child extension like <see cref="ExtGeospatialCrsWkid"/> or <see cref="ExtGeospatialCrsWkt2"/>.
    /// </summary>
    partial class ExtGeospatialCrs
    {
        /// <summary>The CRS format, usually "wkid" or "wkt2".</summary>
        public string Format { get => _format; set => _format = value; }
    }

    /// <summary>
    /// EXT_geospatial_crs_wkid extension, attached to a <see cref="ExtGeospatialCrs"/>.
    /// </summary>
    partial class ExtGeospatialCrsWkid
    {
        public string Authority { get => _authority; set => _authority = value; }

        public int Wkid { get => _wkid; set => _wkid = value; }

        public int? VcsWkid { get => _vcsWkid; set => _vcsWkid = value; }

        /// <summary>Epoch for coordinates referenced to a dynamic CRS, expressed as a decimal year (e.g. "2019.81").</summary>
        public string Epoch { get => _epoch; set => _epoch = value; }
    }

    /// <summary>
    /// EXT_geospatial_crs_wkt2 extension, attached to a <see cref="ExtGeospatialCrs"/>.
    /// </summary>
    partial class ExtGeospatialCrsWkt2
    {
        /// <summary>A Well-Known Text (version 2) string.</summary>
        public string Wkt2 { get => _wkt2; set => _wkt2 = value; }
    }

    #endregion

    #region EXT_node_visibility_*

    /// <summary>
    /// A bounding volume, as defined in glTF 2.1.
    /// </summary>
    partial class Tiles3DBoundingVolume
    {
        public Quaternion Rotation { get => _rotation ?? _rotationDefault; set => _rotation = value == _rotationDefault ? null : value; }

        public Vector3 Scale { get => _scale ?? _scaleDefault; set => _scale = value == _scaleDefault ? null : value; }

        public Vector3 Translation { get => _translation ?? _translationDefault; set => _translation = value == _translationDefault ? null : value; }

        /// <summary>The index of the shape in the top level glTF 2.1 "shapes" array.</summary>
        public int Shape { get => _shape; set => _shape = value; }
    }

    /// <summary>
    /// EXT_node_visibility_volume extension, an extension of KHR_node_visibility.
    /// </summary>
    partial class ExtNodeVisibilityVolume
    {
        public Tiles3DBoundingVolume BoundingVolume { get => _boundingVolume; set => _boundingVolume = value; }
    }

    /// <summary>
    /// EXT_node_visibility_conditions extension, an extension of KHR_node_visibility.
    /// </summary>
    partial class ExtNodeVisibilityConditions
    {
        /// <summary>The conditions, as a dictionary of condition names and their values.</summary>
        public IDictionary<string, JsonNode> Conditions
        {
            get => _conditions;
            set => _conditions = value == null ? null : new Dictionary<string, JsonNode>(value);
        }
    }

    /// <summary>
    /// EXT_node_visibility_conditions extension, attached to a <see cref="ModelRoot"/>.
    /// </summary>
    partial class ExtNodeVisibilityConditionsRoot
    {
        /// <summary>The dimensions of the conditions. Each item is an object with a "name" and a "domain".</summary>
        public IReadOnlyList<JsonNode> Dimensions
        {
            get => _dimensions;
            set => _dimensions = value == null ? new List<JsonNode>() : new List<JsonNode>(value);
        }
    }

    #endregion

    #region EXT_voxels and 3DTILES_tileset_voxels

    /// <summary>
    /// Voxel padding.
    /// </summary>
    partial class Tiles3DVoxelPadding
    {
        public int[] Before { get => _before.Count == 0 ? null : _before.ToArray(); set { _CheckLength(value, _beforeMinItems, _beforeMaxItems); _before = value == null ? new List<int>() : new List<int>(value); } }

        public int[] After { get => _after.Count == 0 ? null : _after.ToArray(); set { _CheckLength(value, _afterMinItems, _afterMaxItems); _after = value == null ? new List<int>() : new List<int>(value); } }

        private static void _CheckLength(int[] value, int min, int max)
        {
            if (value == null) return;
            Guard.MustBeBetweenOrEqualTo(value.Length, min, max, nameof(value));
        }
    }

    /// <summary>
    /// EXT_voxels extension, attached to a <see cref="Node"/>.
    /// </summary>
    partial class ExtVoxelsNode
    {
        public int[] Dimensions
        {
            get => _dimensions.Count == 0 ? null : _dimensions.ToArray();
            set { if (value != null) Guard.MustBeBetweenOrEqualTo(value.Length, _dimensionsMinItems, _dimensionsMaxItems, nameof(value)); _dimensions = value == null ? new List<int>() : new List<int>(value); }
        }

        public Tiles3DVoxelPadding Padding { get => _padding; set => _padding = value; }

        /// <summary>Maps attribute names to accessor indices.</summary>
        public IDictionary<string, int> Attributes
        {
            get => _attributes;
            set => _attributes = value == null ? new Dictionary<string, int>() : new Dictionary<string, int>(value);
        }

        /// <summary>Maps attribute names to the values that represent missing data.</summary>
        public IDictionary<string, double[]> NoData
        {
            get => _noData;
            set => _noData = value == null ? new Dictionary<string, double[]>() : new Dictionary<string, double[]>(value);
        }
    }

    /// <summary>
    /// 3DTILES_tileset_voxels extension, attached to a <see cref="ModelRoot"/>.
    /// </summary>
    partial class Tiles3DTilesetVoxels
    {
        public int[] Dimensions
        {
            get => _dimensions.Count == 0 ? null : _dimensions.ToArray();
            set { if (value != null) Guard.MustBeBetweenOrEqualTo(value.Length, _dimensionsMinItems, _dimensionsMaxItems, nameof(value)); _dimensions = value == null ? new List<int>() : new List<int>(value); }
        }

        public Tiles3DVoxelPadding Padding { get => _padding; set => _padding = value; }

        /// <summary>The metadata class ID that property values conform to.</summary>
        public string Class { get => _class; set => _class = value; }
    }

    #endregion

    #region 3DTILES_horizon_occlusion_point, 3DTILES_implicit_tiling, 3DTILES_tileset*

    /// <summary>
    /// 3DTILES_horizon_occlusion_point extension.
    /// </summary>
    partial class Tiles3DHorizonOcclusionPoint
    {
        /// <summary>The horizon occlusion point in an ellipsoid-scaled fixed frame (3 values).</summary>
        public double[] HorizonOcclusionPoint
        {
            get => _horizonOcclusionPoint.Count == 0 ? null : _horizonOcclusionPoint.ToArray();
            set { if (value != null) Guard.MustBeBetweenOrEqualTo(value.Length, _horizonOcclusionPointMinItems, _horizonOcclusionPointMaxItems, nameof(value)); _horizonOcclusionPoint = value == null ? new List<double>() : new List<double>(value); }
        }
    }

    /// <summary>
    /// 3DTILES_implicit_tiling extension, attached to a <see cref="Node"/>.
    /// </summary>
    partial class Tiles3DImplicitTiling
    {
        public string ContentUri { get => _contentUri; set => _contentUri = value; }

        public string SubtreeUri { get => _subtreeUri; set => _subtreeUri = value; }

        public Tiles3DSubdivisionScheme SubdivisionScheme { get => _subdivisionScheme; set => _subdivisionScheme = value; }

        public int AvailableLevels
        {
            get => _availableLevels;
            set { Guard.MustBeGreaterThanOrEqualTo(value, _availableLevelsMinimum, nameof(value)); _availableLevels = value; }
        }

        public int SubtreeLevels
        {
            get => _subtreeLevels;
            set { Guard.MustBeGreaterThanOrEqualTo(value, _subtreeLevelsMinimum, nameof(value)); _subtreeLevels = value; }
        }
    }

    /// <summary>
    /// 3DTILES_tileset extension, attached to a <see cref="ModelRoot"/>.
    /// </summary>
    partial class Tiles3DTilesetRoot
    {
        public double GeometricError
        {
            get => _geometricError;
            set { Guard.MustBeGreaterThanOrEqualTo(value, _geometricErrorMinimum, nameof(value)); _geometricError = value; }
        }
    }

    /// <summary>
    /// Content of a 3DTILES_tileset node extension.
    /// </summary>
    partial class Tiles3DTilesetContent
    {
        public Tiles3DBoundingVolume BoundingVolume { get => _boundingVolume; set => _boundingVolume = value; }
    }

    /// <summary>
    /// 3DTILES_tileset extension, attached to a <see cref="Node"/>.
    /// </summary>
    partial class Tiles3DTilesetNode
    {
        public double GeometricError
        {
            get => _geometricError;
            set { Guard.MustBeGreaterThanOrEqualTo(value, _geometricErrorMinimum, nameof(value)); _geometricError = value; }
        }

        public Tiles3DRefineType? Refine { get => _refine; set => _refine = value; }

        public Tiles3DTilesetContent Content { get => _content; set => _content = value; }
    }

    /// <summary>
    /// 3DTILES_tileset_vectors extension, attached to a <see cref="ModelRoot"/>.
    /// </summary>
    partial class Tiles3DTilesetVectors
    {
        /// <summary>Whether content should be clipped to tile bounds when rendering.</summary>
        public bool Clip { get => _clip ?? _clipDefault; set => _clip = value == _clipDefault ? null : value; }
    }

    #endregion

    #region 3DTILES_layers

    /// <summary>
    /// A layer defined in <see cref="Tiles3DLayersRoot"/>.
    /// </summary>
    partial class Tiles3DLayer
    {
    }

    /// <summary>
    /// 3DTILES_layers extension, attached to a <see cref="ModelRoot"/>.
    /// </summary>
    partial class Tiles3DLayersRoot
    {
        public IReadOnlyList<Tiles3DLayer> Layers
        {
            get => _layers;
            set { if (value != null) Guard.MustBeGreaterThanOrEqualTo(value.Count, _layersMinItems, nameof(value)); _layers = value == null ? new List<Tiles3DLayer>() : new List<Tiles3DLayer>(value); }
        }
    }

    /// <summary>
    /// 3DTILES_layers extension, attached to a <see cref="Node"/>.
    /// </summary>
    partial class Tiles3DLayersNode
    {
        /// <summary>Index of the layer in <see cref="Tiles3DLayersRoot.Layers"/>.</summary>
        public int Layer { get => _layer; set => _layer = value; }
    }

    #endregion

    #region 3DTILES_subtree

    /// <summary>
    /// Availability of a set of elements in a <see cref="Tiles3DSubtree"/>.
    /// </summary>
    partial class Tiles3DSubtreeAvailability
    {
        /// <summary>Index of the buffer view containing the availability bitstream.</summary>
        public int? Bitstream { get => _bitstream; set => _bitstream = value; }

        public int? AvailableCount
        {
            get => _availableCount;
            set { if (value.HasValue) Guard.MustBeGreaterThanOrEqualTo(value.Value, _availableCountMinimum, nameof(value)); _availableCount = value; }
        }

        /// <summary>Indicates whether all elements are available or all are unavailable.</summary>
        public Tiles3DAvailabilityConstant? Constant { get => _constant; set => _constant = value; }
    }

    /// <summary>
    /// 3DTILES_subtree extension, attached to a <see cref="ModelRoot"/>.
    /// </summary>
    partial class Tiles3DSubtree
    {
        public Tiles3DSubtreeAvailability TileAvailability { get => _tileAvailability; set => _tileAvailability = value; }

        public Tiles3DSubtreeAvailability ContentAvailability { get => _contentAvailability; set => _contentAvailability = value; }

        public Tiles3DSubtreeAvailability ChildSubtreeAvailability { get => _childSubtreeAvailability; set => _childSubtreeAvailability = value; }

        /// <summary>Maps tile attribute semantics to accessor indices.</summary>
        public IDictionary<string, int> TileAttributes
        {
            get => _tileAttributes;
            set => _tileAttributes = value == null ? null : new Dictionary<string, int>(value);
        }

        /// <summary>Maps content attribute semantics to accessor indices.</summary>
        public IDictionary<string, int> ContentAttributes
        {
            get => _contentAttributes;
            set => _contentAttributes = value == null ? null : new Dictionary<string, int>(value);
        }

        /// <summary>Index of the property table containing tile properties.</summary>
        public int? TileProperties { get => _tileProperties; set => _tileProperties = value; }

        /// <summary>Index of the property table containing content properties.</summary>
        public int? ContentProperties { get => _contentProperties; set => _contentProperties = value; }
    }

    #endregion

    #region 3DTILES_shape_*

    /// <summary>
    /// 3DTILES_shape_cylinder_region extension.
    /// </summary>
    partial class Tiles3DShapeCylinderRegion
    {
        public double MinimumRadius
        {
            get => _minimumRadius;
            set { Guard.MustBeGreaterThanOrEqualTo(value, _minimumRadiusMinimum, nameof(value)); _minimumRadius = value; }
        }

        public double MaximumRadius
        {
            get => _maximumRadius;
            set { Guard.MustBeGreaterThanOrEqualTo(value, _maximumRadiusMinimum, nameof(value)); _maximumRadius = value; }
        }

        public double Height
        {
            get => _height;
            set { Guard.MustBeGreaterThanOrEqualTo(value, _heightMinimum, nameof(value)); _height = value; }
        }

        /// <summary>Minimum angle in radians.</summary>
        public double MinimumAngle { get => _minimumAngle ?? _minimumAngleDefault; set => _minimumAngle = value == _minimumAngleDefault ? null : value; }

        /// <summary>Maximum angle in radians.</summary>
        public double MaximumAngle { get => _maximumAngle ?? _maximumAngleDefault; set => _maximumAngle = value == _maximumAngleDefault ? null : value; }
    }

    /// <summary>
    /// 3DTILES_shape_ellipsoid_region extension.
    /// </summary>
    partial class Tiles3DShapeEllipsoidRegion
    {
        public double MinimumHeight { get => _minimumHeight; set => _minimumHeight = value; }

        public double MaximumHeight { get => _maximumHeight; set => _maximumHeight = value; }

        /// <summary>Minimum latitude in radians.</summary>
        public double MinimumLatitude
        {
            get => _minimumLatitude ?? _minimumLatitudeDefault;
            set { Guard.MustBeBetweenOrEqualTo(value, _minimumLatitudeMinimum, _minimumLatitudeMaximum, nameof(value)); _minimumLatitude = value == _minimumLatitudeDefault ? null : value; }
        }

        /// <summary>Maximum latitude in radians.</summary>
        public double MaximumLatitude
        {
            get => _maximumLatitude ?? _maximumLatitudeDefault;
            set { Guard.MustBeBetweenOrEqualTo(value, _maximumLatitudeMinimum, _maximumLatitudeMaximum, nameof(value)); _maximumLatitude = value == _maximumLatitudeDefault ? null : value; }
        }

        /// <summary>Minimum longitude in radians.</summary>
        public double MinimumLongitude { get => _minimumLongitude ?? _minimumLongitudeDefault; set => _minimumLongitude = value == _minimumLongitudeDefault ? null : value; }

        /// <summary>Maximum longitude in radians.</summary>
        public double MaximumLongitude { get => _maximumLongitude ?? _maximumLongitudeDefault; set => _maximumLongitude = value == _maximumLongitudeDefault ? null : value; }
    }

    /// <summary>
    /// 3DTILES_shape_s2 extension.
    /// </summary>
    partial class Tiles3DShapeS2
    {
        /// <summary>Hexadecimal representation of the S2CellId.</summary>
        public string Token { get => _token; set => _token = value; }

        public double MinimumHeight { get => _minimumHeight; set => _minimumHeight = value; }

        public double MaximumHeight { get => _maximumHeight; set => _maximumHeight = value; }
    }

    #endregion
}
